# Generated by Django 5.2.4 on 2025-07-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_created_at_comment_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
