# Generated by Django 5.2.4 on 2025-07-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
